#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

if grep -q '^dnsSecondary=' ${syscfg}; then dnsWithSecondary=Y; fi
if grep -q '^dnsPrimary=' ${syscfg}; then dnsWithPrimary=Y; fi

dnscp="cp"
dnsbase="/ram/dns"
if test "${dnsLogging}" = "Y" \
	-o "${dnsWithSecondary}" = "Y" \
	-o "${dnsWithPrimary}" = "Y"
	then
		dnsbase="/opt/data/dns"
		dnscp="ln"
	fi

