#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

if grep -q '^namedSlave=' ${syscfg}; then namedWithSlave=Y; fi

namedbase="/ram/named"
if test "${namedLogging}" = "Y" -o "${namedWithSlave}" = "Y"
	then
		namedbase="/opt/data/named"
	fi

