#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

syscfg="/opt/config/system.cfg"

. ${syscfg}

if test -z "${static4IP}" -a -f /ram/dhcp/eth0
	then
		. /ram/dhcp/eth0
		my4ip="${eth0_ip}/${eth0_subnet}"
		my4gw="${eth0_router}"
	else
		my4ip="${static4IP}"
		my4gw="${static4GW}"
	fi
	
if test "${my4ip}"
	then
		tmp=/tmp/opts_$$_$RANDOM
		{
		ipcalc -pbnm ${my4ip} | awk '{ print "my4" _ tolower($0) }'
		echo "${my4ip}" | awk -F/ '{ printf "my4addr=%s\n",$1 }'
		} > ${tmp}
		. ${tmp}
		rm -f ${tmp}
	fi
