#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

syscfg="/opt/config/system.cfg"

. ${syscfg}

if test -z "${staticResolvers}" -a "${static4IP}"
	then
		staticResolvers="8.8.8.8 8.8.4.4 208.67.220.220 208.67.222.222"
	fi
