#! /bin/bash

uid=$(id -u)
if ! test "${uid}" = "0"
    then
        echo "***********************************************************"
        echo ""
        echo "Becuase you are not UID=0 (root), I will need to use 'sudo'"
        echo ""
        echo "***********************************************************"
        sudo ./tstroot $*
        exit 0
    fi

mount -o noexec -t devtmpfs dev ROOT/dev
mount -o noexec -t proc proc ROOT/proc
mount -o noexec -t sysfs sys ROOT/sys
mount -t tmpfs -o noexec,size=3M ram ROOT/ram
mount -t tmpfs -o noexec,size=3M ram ROOT/opt/config
mount -t tmpfs -o noexec,size=3M ram ROOT/opt/data
mkdir ROOT/ram/run ROOT/ram/tmp ROOT/ram/root ROOT/ram/db
chmod 700 ROOT/ram/root
chown 0:0 ROOT/ram/tmp ROOT/ram/run ROOT/ram/root
chmod 777 ROOT/ram/tmp ROOT/ram/run
chmod +t ROOT/ram/tmp ROOT/ram/run

cat ROOT/etc/base_config/* > ROOT/opt/config/system.cfg

chroot ROOT /usr/scripts/make_shadow
chroot ROOT /etc/rc.d/boot.d/20_roothome
export HOME="/ram/root"
chroot ROOT /bin/sh -li

umount ROOT/proc ROOT/sys ROOT/dev \
	ROOT/ram ROOT/opt/config ROOT/opt/data
