#! /bin/sh

echo "========================================================"
echo "Running boot-script"

mount -nt proc /proc /proc
mount -nt sysfs /sys /sys
mount -t tmpfs -no size=3M /tmp /tmp
mount -rno remount /

hostname install.zz.

echo "" > /dev/tty5

switch_screen 5
