#! /bin/sh

set -x

mount -rno remount /

echo "Running boot-script"

mount -nt proc /proc /proc
mount -t tmpfs -no size=3M /tmp /tmp

hostname install.zz.

echo "" > /dev/tty5

switch_screen 5

/usr/bin/kbdrate -r 2 -d 1000
