#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

. /usr/scripts/opts

if test "${dnsWithAS112}" = "Y"
	then
		for ip in 192.175.48.1 192.175.48.6 192.175.48.42 192.31.196.1
			do
				ip -4 add addr ${ip}/32 dev eth0 >/dev/null 2>&1
			done
			
		for ip in 2620:4f:8000::1 2620:4f:8000::6 2620:4f:8000::42 2001:4:112::1
			do
				ip -6 addr add ${ip}/128 dev eth0 >/dev/null 2>&1
			done
	fi
