#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details
#
# Also a lot lifted from RFC7534
# https://tools.ietf.org/html/rfc7534

. /usr/scripts/opts

tmp=/tmp/make_named_conf_$$_$RANDOM
dst="${namedbase}/etc/named.conf"

{
echo 'options {
   listen-on {
       127.0.0.1;         // localhost

     // The following address is node-dependent and should be set to
     // something appropriate for the new AS112 node.

'
echo "       ${my4ip};       // local address (globally unique, unicast)"


if test "${namedWithAS112}" = "Y"
then
echo '
     // The following addresses are used to support Direct Delegation
     // AS112 service and are the same for all AS112 nodes.

       192.175.48.1;      // prisoner.iana.org (anycast)
       192.175.48.6;      // blackhole-1.iana.org (anycast)
       192.175.48.42;     // blackhole-2.iana.org (anycast)

     // The following address is used to support DNAME redirection
     // AS112 service and is the same for all AS112 nodes.

       192.31.196.1;      // blackhole.as112.arpa (anycast)'
fi

echo '};

     listen-on-v6 {
       ::1;               // localhost
   '

if test "${namedWithAS112}" = "Y"
then
echo '
     // The following addresses are used to support Direct Delegation
     // AS112 service and are the same for all AS112 nodes.

       2620:4f:8000::1;   // prisoner.iana.org (anycast)
       2620:4f:8000::6;   // blackhole-1.iana.org (anycast)
       2620:4f:8000::42;  // blackhole-2.iana.org (anycast)

     // The following address is used to support DNAME redirection
     // AS112 service and is the same for all AS112 nodes.

       2001:4:112::1;    // blackhole.as112.arpa (anycast)
'
fi


if test "${static6IP}"
	then
		echo "      ${static6IP};"
	fi
echo '
     };

     directory "/var/named";
     allow-update { none; };
     notify no;
     listen-on-v6 { any; };
     max-udp-size 4096;
     edns-udp-size 4096;
'

if test "${namedDNSSEC}" = "Y"
	then
	     echo "dnssec-enable yes;"
	else
	     echo "dnssec-enable no;"
	fi

if test "${namedResolver}" = "Y"
	then
	     echo "    recursion yes;"
	     if test "${resolverAllowed}"
	     	then
	     		echo -n "    allow-recursion { 127.0.0.0/8; ::1; "
	     		for svr in ${resolverAllowed}
	     		do	
	     			echo -n "${svr}; "
	     		done
	     		echo "};"
	     	fi
	else
	     echo "    recursion no;        // authoritative-only server"
	fi
     
echo ' };  '

if test "${namedLogging}" = "Y"
	then
	echo "// namedLogging = ${namedLogging}"
echo '
   // Log queries, so that when people call us about unexpected
   // answers to queries they did not realise they had sent, we
   // have something to talk about.  Note that activating this
   // naively has the potential to create high CPU load and consume
   // enormous amounts of disk space.  This example retains 2 old
   // versions at a maximum of 500 MB each before rotating out the
   // oldest one.

logging {
     channel "querylog" {
       file "/var/log/query.log" versions 2 size 500m;
       print-time yes;
     };
     category queries { querylog; };
   };
'
fi



if test -f /opt/config/rndc.conf
	then
		cp /opt/config/rndc.conf /ram/rndc.conf
elif test "${namedRndcKey}"
	then
		echo "key \"rndc-key\" { algorithm hmac-md5; secret \"${namedRndcKey}\"; };"
		echo "controls {"
		echo "   inet 127.0.0.1 port 953 allow { 127.0.0.1; } keys { \"rndc-key\"; };"
		
		if test "${namedRndcAllow}" -a ! "${namedRndcAllow}" = "127.0.0.1"
			then
				rtmp="/tmp/make_named_conf_$$_$RANDOM"
				/usr/scripts/by_addr_type 0 ${namedRndcAllow} > ${rtmp}
				
				if test "${my4ip}" && grep -q " 4 " ${rtmp}
					then
						awk 'BEGIN { printf "\tinet '"${my4ip}"' port 953 allow { " }
						{ if ($3=="4") printf "%s; ",$NF }
						END { print "} keys { \"rndc-key\"; };"
						}' ${rtmp}
					fi
				if test "${my4ip}" && grep -q " 6 " ${rtmp}
					then
						awk 'BEGIN  printf "\tinet '"${static6IP}"' port 953 allow { " }
						{ if ($3=="6") printf "%s; ",$NF }
						END { print "} keys { \"rndc-key\"; };"
						}' ${rtmp}
					fi
					
				rm -f ${rtmp}
			fi
		echo "};"

		{
		echo "key \"rndc-key\" { algorithm hmac-md5; secret \"${namedRndcKey}\"; };"
		echo "options { default-key \"rndc-key\"; default-server 127.0.0.1; default-port 953; };"
		} > /ram/rndc.conf
fi



if test "${namedWithAS112}" = "Y"
then
echo '
   // Direct Delegation AS112 Service

   // RFC 1918

zone "10.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "16.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "17.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "18.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "19.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "20.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "21.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "22.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "23.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "24.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "25.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "26.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "27.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "28.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "29.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "30.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "31.172.in-addr.arpa" { type master; file "db.dd-empty"; };
zone "168.192.in-addr.arpa" { type master; file "db.dd-empty"; };

   // RFC 6890

zone "254.169.in-addr.arpa" { type master; file "db.dd-empty"; };

   // DNAME redirection AS112 Service

zone "empty.as112.arpa" { type master; file "db.dr-empty"; };

   // Also answer authoritatively for the HOSTNAME.AS112.NET and
   // HOSTNAME.AS112.ARPA zones, which contain data of operational
   // relevance.

zone "hostname.as112.net" {
     type master;
     file "db.hostname.as112.net";
   };

zone "hostname.as112.arpa" {
     type master;
     file "db.hostname.as112.arpa";
   };
'
fi

if test "${namedWithSlave}" = "Y"
	then
		mkdir -p ${namedbase}/slave
		chown nobody: ${namedbase}/slave

		awk '/^namedSlave=/ {
			x=substr($0,index($0,"=")+1);
			gsub("\"","",x);
			n=split(x,a," ");

			file=a[1];
			gsub("/","_",file);
			gsub(":","_",file);

			printf "zone \"%s\" { type slave; file \"/slave/%s\"; masters {",a[1],file
			for(l=2;l<=n;l++) printf "%s; ",a[l]
			print "}; };"

			}' ${syscfg}
	fi

} > ${tmp}

mv ${tmp} ${dst}


if ! /usr/sbin/named-checkconf -t ${namedbase}
	then
		logger -s -t "named-checkconf" "ERROR: named.conf failed validation checks"
	else
		killall -q -HUP named
	fi
