#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

. /usr/scripts/opts

mkdir -p ${dnsbase}
cd ${dnsbase}

mkdir -p dev
cp -a /dev/random /dev/urandom /dev/null /dev/zero dev
mkdir -p etc

mkdir -p var var/dns var/log var/run var/run/dns
chmod 777 var/log var/run var/run/dns
chmod 755 . dev var etc
chown nobody: var/dns

if test "${dnsWithAS112}" = "Y"
	then
		/usr/scripts/make_db.hostname.as112

		cp -a /opt/dns/etc/db.as112.arpa \
			/opt/dns/etc/db.dd-empty \
			/opt/dns/etc/db.dr-empty \
			var/dns
	fi

/usr/scripts/make_dns_conf

if ! named-checkconf -t ${dnsbase}
	then
		logger -s -t "start_dns" "dns.conf failed named-checkconf"
		exec sleep 100
	fi

exec /usr/sbin/named -u nobody -t ${dnsbase} -f
