#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

dmesg -n 5

mount -o noexec -t proc /proc /proc
mount -o noexec -t sysfs /sys /sys
mkdir /dev/pts
mount -o noexec -t devpts /dev/pts /dev/pts

fsck -A -y
mount -a
mount -ro remount,noatime /
swapon -a

if test -d /etc/config -a ! -f /opt/config/system.cfg
	then
		cd /etc/config
		cp -a . /opt/config
	fi
if test ! -f /opt/config/system.cfg
	then
		cat /etc/base_config/* > /opt/config/system.cfg
	fi

if test -f /opt/config/seed.rnd; then cat /opt/config/seed.rnd > /dev/urandom; fi

mount -t tmpfs -o noexec,size=3M RamDISK /ram
cd /ram
mkdir ssh root tmp etc run net-snmp db
chmod 777 run tmp
chmod +t run tmp
touch etc/adjtime

chown 0:0 /opt/config/system.cfg /ram/ssh /ram/root
chmod 600 /opt/config/system.cfg /ram/ssh /ram/root

if test -f /opt/config/busybox.conf
	then
		ln -s /opt/config/busybox.conf /ram/etc/busybox.conf
	else
		touch /ram/etc/busybox.conf
	fi

touch /ram/just-booted

mkdir -m 700 root/.ssh
/usr/scripts/make_auth_keys

ip link set lo up

mkdir -p /opt/data/log
touch /var/log/lastlog /var/log/wtmp

/usr/scripts/make_inittab
/usr/scripts/make_shadow

. /usr/scripts/opts
hostname ${serverHostname}

mapfile="/etc/kmap/uk.bmap.gz"
if test "${keyboardMap}" -a -f /etc/kmap/${keyboardMap}.bmap.gz
	then
		mapfile="/etc/kmap/${keyboardMap}.bmap.gz"
	fi
zcat ${mapfile} | loadkmap

if test -f /opt/config/install.cfg
	then
		. /opt/config/install.cfg
		desc="${baseos}: ${overlays}"
	else
		desc="SlimLinux"
	fi

awk '{ 
	printf "\n%s\nKernel v%s\n\n","'"${desc}"'",$3
	}' /proc/version > /ram/etc/motd
