#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

dmesg -n 5

mount -o noexec -t proc /proc /proc
mount -o noexec -t sysfs /sys /sys
mkdir /dev/pts
mount -o noexec -t devpts /dev/pts /dev/pts

fsck -A -y
mount -a
mount -ro remount,noatime /
awk '{ if ($3=="swap") print $1 }' /etc/fstab | while read dev
do
	mkswap ${dev}
done
swapon -a

if test -f /opt/config/seed.rnd; then cat /opt/config/seed.rnd > /dev/urandom; fi

mount -t tmpfs -o noexec,size=3M /ram /ram
cd /ram
mkdir ssh root tmp etc run net-snmp
chmod 777 run tmp
chmod +t run tmp
touch etc/adjtime

chown 0:0 /opt/config/system.cfg /ram/ssh /ram/root
chmod 600 /opt/config/system.cfg /ram/ssh /ram/root

touch /ram/just-booted

mkdir -m 700 root/.ssh
/usr/scripts/make_auth_keys

ip link set lo up

mkdir -p /opt/data/log
touch /var/log/lastlog /var/log/wtmp

/usr/scripts/make_inittab
/usr/scripts/make_shadow

. /usr/scripts/opts
hostname ${serverHostname}

mapfile="/etc/kmap/uk.bmap.gz"
if test "${keyboardMap}" -a -f /etc/kmap/${keyboardMap}.bmap.gz
	then
		mapfile="/etc/kmap/${keyboardMap}.bmap.gz"
	fi
zcat ${mapfile} | loadkmap

if test -f /opt/config/install.cfg
	then
		. /opt/config/install.cfg
		desc="${baseos}: ${overlays}"
	else
		desc="SlimLinux"
	fi

awk '{ 
	printf "\n%s\nKernel v%s\n\n","'"${desc}"'",$3
	}' /proc/version > /ram/etc/motd
