#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

. /usr/scripts/opts

{
echo "
alias h='history'
alias ls='ls --color=auto'
alias l='ls -lL'
alias ro='mount -rno remount,async /'
alias rw='mount -wno remount,sync,noatime,nodiratime /'
alias rwr='mount -wno remount,async,noatime,nodiratime /'
alias psx='ps -o pid,ppid,vsz,rss,nice,user,time,args'
alias fls='find . -exec ls -ld {} \";\"'
alias more=less
alias ifc=\"ip addr | grep -E '(,UP,| scope )'\"

export EXINIT='set tabstop=4 ai'
export PATH=/sbin

"
echo "if tty -s ; then echo -ne '\e]2;${serverHostname}\a'; fi"

} > /ram/root/.profile

