#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details


if test "${allowConsoleLogin}" = "Y"
	then
		echo "--------------- Press Atl-F2 to Login  ---------------"
	else
		echo "------------------ Boot Complete ---------------------"
	fi
