#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details
#

killall bgpd 2>/dev/null

if test -f /opt/config/bgpd.conf
	then
		exec /usr/sbin/bgpd -f /opt/config/bgpd.conf
		exit 0
	fi

/usr/scripts/make_bgpd_conf

exec /usr/sbin/bgpd -f /ram/etc/bgpd.conf
