#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

if test -f /opt/config/zebra.conf
	then
		exec /usr/sbin/zebra -f /opt/config/zebra.conf
		exit 0
	fi

. /usr/scripts/opts

{
echo "! zebra.conf
hostname ${serverHostname}"

if test "${bgpPassword}"; then echo "password ${bgpPassword}"; else echo "password aa"; fi
if test "${bgpEditPassword}"; then echo "enable password ${bgpEditPassword}"; fi

echo "interface lo"
echo "interface eth0"
}  > /ram/etc/zebra.conf

cfg="/ram/etc/zebra.conf"
chown quagga: ${cfg}
chmod 400 ${cfg}

exec /usr/sbin/zebra -f ${cfg}
