#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details


if test "${resolverActive}" = "Y"
    then
		echo "nameserver 127.0.0.1" > /ram/etc/resolv.conf
	fi


if test \( "${static4IP}" -a "${static4Mask}" \) \
	-o \( "${static6IP}" -a "${static6Mask}" \)
		then
			/usr/scripts/add_as112_ips
		fi
