#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

. /usr/scripts/opts

{
echo "iptables 4"
echo "ip6tables 6"
} | while read cmd ipv
do
	if test -f /opt/config/${cmd}.conf
		then
			cp /opt/config/${cmd}.conf /ram/etc/${cmd}.conf
		else
			tmp=/ram/etc/${cmd}.conf_$$_$RANDOM
			for file in /usr/scripts/make_firewall.d/*; do . ${file}; done > ${tmp}
			mv ${tmp} /ram/etc/${cmd}.conf
		fi

	if ${cmd}-restore < /ram/etc/${cmd}.conf
		then
			rm -f /ram/etc/${cmd}.conf.bz2
			bzip2 /ram/etc/${cmd}.conf
		else
			echo "ERROR: ${cmd}-restore"
		fi
done
