#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

. /usr/scripts/opts

/usr/scripts/make_auth_keys

mkdir -p /ram/ssh
xz -dc /etc/moduli.xz > /ram/ssh/moduli
if test -d /opt/config/ssh
	then
		cp -a /opt/config/ssh/* /ram/ssh
	else
		ssh-keygen -A
		mkdir -p /opt/config/ssh
		cp -a /etc/ssh/ssh_host_* /opt/config/ssh
	fi

tmp=/ram/tmp/make_sshd_config_$$_$RANDOM
{
if test "${allowRootSSH}" = "Y"
	then
		echo "PermitRootLogin Yes"
	fi
echo "PubkeyAcceptedKeyTypes=+ssh-dss,ssh-rsa"
} > ${tmp}

dst=/ram/ssh/sshd_config
chmod 400 ${tmp}
mv ${tmp} ${dst}
rm -f ${tmp}

exec /usr/sbin/sshd -D
