#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

. /usr/scripts/opts

killall -q snmpd

if test -f /opt/config/snmpd.conf
	then
		exec /usr/sbin/snmpd -u nobody -r -f -c /opt/config/snmpd.conf
		exit 0
	fi



{
echo "com2sec   public    default       public

group  worldGroup  v1         public
group  worldGroup  v2c        public
group  myGroup     v1         mynet
group  myGroup     v2c        mynet

view   sysView included    system
view   sysView included    .1.3.6.1.2.1.25.1
view   sysView included    .1.3.6.1.2.1.2.2.1

access  worldGroup  \"\"  any  noauth  exact   sysView  none   none
"
} > /ram/etc/snmpd.conf

exec /usr/sbin/snmpd -u nobody -r -f -c /ram/etc/snmpd.conf
