#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

if test "${action}" = "bound"
	then
		/usr/scripts/add_as112_ips "${interface}"
	fi
