#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

local=$(awk '{ printf "%s:%s\n",$1,$2}' /proc/sys/net/ipv4/ip_local_port_range)

echo "*filter"
echo ":INPUT ACCEPT [0:0]"
echo ":FORWARD ACCEPT [0:0]"
echo ":OUTPUT ACCEPT [0:0]"
