#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

if test "${runningSSHd}" = "Y"
	then
		if test "${sshRemoteAllow}"
			then
				/usr/scripts/by_addr_type ${ipv} ${sshRemoteAllow} | while read adr msk typ all
				do
					echo "-A INPUT -p tcp -s ${all} --dport 22 -j ACCEPT"
					echo "-A OUTPUT -p tcp -d ${all} --sport 22 -j ACCEPT"
				done
			else
				echo "-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT"
				echo "-A OUTPUT -p tcp -m tcp --sport 22 -j ACCEPT"
			fi
	fi
