#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

if test "${runningBGPd}" = "Y"
	then
		echo "zba:45:respawn:/usr/scripts/start_zebra"
		echo "bgp:5:respawn:/usr/scripts/start_bgpd"
	fi
