#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details


deflevel=2
if test "${static4IP}"
	then
		deflevel=5
	fi

echo "id:${deflevel}:initdefault:"

echo "si:S:sysinit:/etc/rc.d/boot"
echo "ca::ctrlaltdel:/sbin/init 6"
echo "l0:0:wait:/etc/rc.d/close poweroff"
echo "l6:6:wait:/etc/rc.d/close reboot"
echo ""

echo "hd:2345:respawn:/usr/sbin/haveged -F >/tmp/haveged.log 2>&1"

if test "${allowConsoleLogin}" = "Y"
	then
		echo "c2:12345:respawn:/sbin/getty 38400 tty2 linux"
		echo "c3:12345:respawn:/sbin/getty 38400 tty3 linux"
		echo "c4:12345:respawn:/sbin/getty 38400 tty4 linux"
	fi
	
echo ""

if test "${syslogToDisk}" = "Y"
	then
		if test "${syslogSize}"
			then
				extra_syslog="-s ${syslogSize}"
			fi
		echo "sl:2345:respawn:/sbin/syslogd -n -b 5 -D ${extra_syslog}"
	else
		echo "sl:2345:respawn:/sbin/syslogd -n -C100"
	fi
echo "kl:2345:respawn:/sbin/klogd -n"
echo "ap:2345:respawn:/sbin/acpid -d -f >/dev/tty9 2>&1"

echo ""

if test -z "${static4IP}"
	then
		echo "dh:2345:respawn:/sbin/udhcpc -f -s /usr/scripts/udhcpc.script -S >/dev/null 2>&1"
	fi

echo ""
echo "cr:345:respawn:/sbin/crond -l 10 -c /var/cron -f"

if test "${ntpServers}"
	then
		echo "ntp:345:respawn:/usr/scripts/start_ntpd"
	fi

# allow some entropy to accumulate before running sshd
echo "wt:5:wait:/sbin/sleep 1 >/tmp/sleep.log 2>&1"

if test "${runningSSHd}" = "Y"
	then
		echo "sd:345:respawn:/usr/scripts/start_sshd"
	fi
