#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details

end_cmd="$1"

dd if=/dev/urandom of=/opt/config/seed.rnd bs=512 count=1 >/dev/null 2>&1 &

killall5 -15
sleep 3
killall5 -9

swapoff -a
sync
wait
umount -a
mount -v -no remount,ro /

sync

echo "Running - ${end_cmd}"
${end_cmd} -f
