#! /bin/sh
#
# (c) Copyright 2017-2018 James Stevens (james@jrcs.net) - All Rights Reserved
# see License.txt for details


if test "${runningBGPd}" = "Y"
	then
		echo "-A BGPEER -p icmp -j ACCEPT"
		echo "-A BGPEER -p tcp --dport 179 -j ACCEPT"
		echo "-A BGPEER -p tcp --sport 179 -j ACCEPT"

		if test -f /opt/config/bgpd.conf
			then
				awk 'BEGIN { ipv="'"${ipv}"'" }
				/neighbor /&&/ remote-as / {
					ip=$2
					if (((ipv==4)&&(index(ip,".")))||((ipv==6)&&(index(ip,":")))) {
						printf "-A INPUT -s %s -j BGPEER\n",ip
						printf "-A OUTPUT -d %s -j BGPEER\n",ip
						}
					}' /opt/config/bgpd.conf
			else
				awk -F= 'BEGIN { ipv="'"${ipv}"'" }
				/^bgpPeers/ {
					x=substr($0,index($0,"=")+1);
					gsub("\"","",x);
					split(x,a,",");
					ip = a[1];
					if ((((ipv==4)&&(index(ip,".")))||((ipv==6)&&(index(ip,":"))))) {
						printf "-A INPUT -s %s -j BGPEER\n",ip
						printf "-A OUTPUT -d %s -j BGPEER\n",ip
						}
					}' ${syscfg}
			fi
	fi


if test "${bgpRemoteAllow}"
	then
        /usr/scripts/by_addr_type ${ipv} ${bgpRemoteAllow} | while read adr msk typ all
			do
				echo "-A INPUT -p tcp -m tcp -s ${all} --dport 2601 -j ACCEPT"
				echo "-A INPUT -p tcp -m tcp -s ${all} --dport 2605 -j ACCEPT"
				echo "-A OUTPUT -p tcp -m tcp -d ${all} --sport 2601 -j ACCEPT"
				echo "-A OUTPUT -p tcp -m tcp -d ${all} --sport 2605 -j ACCEPT"
			done
	fi

